language: c++
os:
  - linux
  - osx

dist: xenial
compiler: gcc
addons:
  apt:
    packages:
      - freeglut3
      - libglew1.5-dev
      - freeglut3-dev
      - freeglut3-dev
      - libglew1.5
      - libglu1-mesa
      - libglu1-mesa-dev
      - libgl1-mesa-glx
      - libgl1-mesa-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install glew; fi

script:
  - make
