#!/usr/bin/env tcsh
set PROJECT_DIR=`pwd` # /home/samh/cg/assignment3
setenv LD_LIBRARY_PATH /asset/common/software/thirdparty/glew/1.5.1-build3/arch/linux-centos5_2/x86_64/lib:${PROJECT_DIR}/usr/local/lib/
./$1
