version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install buildchain
          command: 'apt-get update && sudo apt-get install -y build-essential'
      - run:
          name: build
          command: 'make all'
