version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install buildchain
          command: 'apt-get update && sudo apt-get install -y build-essential'
      - run:
          name: Install GL toolchain
          command: 'apt-get update && sudo apt-get install -y freeglut3 libglew1.5-dev freeglut3-dev libglew1.5 libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev'

      - run:
          name: build
          command: 'make all'
  build: # runs not using `Workflows` must have a `build` job as entry point
    macos:  # indicate that we are using the macOS executor
      xcode: "9.0.0" # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout
      - run:
          name: Install brew
          command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      - run:
          name: Install GL toolchain
          command: 'brew install glew'

      - run:
          name: build
          command: 'make all'
